name: CI-CICDDashboard-Extension

on:
  push:
    branches: [ Issue0110 ]
  pull_request:
    branches: [ Issue0110 ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1.4.1
      with:
        node-version: '12.x'

    - name: Install Tfx-Cli
      run: npm install -g tfx-cli

    - name: Install Dependencies
      run: npm install

    - name: Compile extension
      run: npm run compile

    - name: Package AzureDevOpsExtension
      run: tfx extension create --json --no-color --manifest-globs vss-extension.json src/ext/**/*.json